name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - run: cargo generate --init https://github.com/alpinus4/bevy-template --name test_project
    - uses: actions-rs/cargo@v1
      with:
        command: build 
