name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - run: sudo apt-get install -y clang mold
    - uses: cargo-generate/cargo-generate-action@v0.17
      with:
        name: test-project
    - run: |
        mv test-project ${{ runner.temp }}/
        cd ${{ runner.temp }}/test-project
        cargo check
